In [1]:
import pandas as pd
df = pd.read_excel("../data/Online Retail.xlsx")
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [2]:
df.shape

(541909, 8)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[us]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 33.1+ MB

In [4]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [5]:
df.head()
df.shape
df.info()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[us]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 33.1+ MB

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [6]:
df["InvoiceNo"].astype(str).str.startswith("C").value_counts()

InvoiceNo
False    532621
True       9288
Name: count, dtype: int64

In [7]:
df["InvoiceNo"].astype(str).str.startswith("C").sum()

np.int64(9288)

In [8]:
df_clean = df[
    ~df["InvoiceNo"].astype(str).str.startswith("C")
].copy()

In [9]:
df_clean.shape

(532621, 8)

In [10]:
df_clean["CustomerID"].isnull().sum()

np.int64(134697)

In [11]:
df_clean = df_clean.dropna(subset=["CustomerID"]).copy()
df_clean.shape

(397924, 8)

In [12]:
(df_clean["Quantity"] <= 0).sum()

np.int64(0)

In [13]:
(df_clean["UnitPrice"] <= 0).sum()

np.int64(40)

In [14]:
df_clean[df_clean["UnitPrice"] <= 0][
    ["InvoiceNo", "StockCode", "Description", "Quantity", "UnitPrice", "CustomerID"]
].head(20)

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID
9302,537197,22841,ROUND CAKE TIN VINTAGE GREEN,1,0.0,12647.0
33576,539263,22580,ADVENT CALENDAR GINGHAM SACK,4,0.0,16560.0
40089,539722,22423,REGENCY CAKESTAND 3 TIER,10,0.0,14911.0
47068,540372,22090,PAPER BUNTING RETROSPOT,24,0.0,13081.0
47070,540372,22553,PLASTERS IN TIN SKULLS,24,0.0,13081.0
56674,541109,22168,ORGANISER WOOD ANTIQUE WHITE,1,0.0,15107.0
86789,543599,84535B,FAIRY CAKES NOTEBOOK A6 SIZE,16,0.0,17560.0
130188,547417,22062,CERAMIC BOWL WITH LOVE HEART DESIGN,36,0.0,13239.0
139453,548318,22055,MINI CAKE STAND HANGING STRAWBERY,5,0.0,13113.0
145208,548871,22162,HEART GARLAND RUSTIC PADDED,2,0.0,14410.0
157042,550188,22636,CHILDS BREAKFAST SET CIRCUS PARADE,1,0.0,12457.0
187613,553000,47566,PARTY BUNTING,4,0.0,17667.0
198383,554037,22619,SET OF 6 SOLDIER SKITTLES,80,0.0,12415.0
279324,561284,22167,OVAL WALL MIRROR DIAMANTE,1,0.0,16818.0
282912,561669,22960,JAM MAKING SET WITH JARS,11,0.0,12507.0
285657,561916,M,Manual,1,0.0,15581.0
298054,562973,23157,SET OF 6 NATIVITY MAGNETS,240,0.0,14911.0
314745,564651,23270,SET OF 2 CERAMIC PAINTED HEARTS,96,0.0,14646.0
314746,564651,23268,SET OF 2 CERAMIC CHRISTMAS REINDEER,192,0.0,14646.0
314747,564651,22955,36 FOIL STAR CAKE CASES,144,0.0,14646.0

In [15]:
df_clean["UnitPrice"].describe()

count    397924.000000
mean          3.116174
std          22.096788
min           0.000000
25%           1.250000
50%           1.950000
75%           3.750000
max        8142.750000
Name: UnitPrice, dtype: float64

In [16]:
df_clean["Quantity"].describe()

count    397924.000000
mean         13.021823
std         180.420210
min           1.000000
25%           2.000000
50%           6.000000
75%          12.000000
max       80995.000000
Name: Quantity, dtype: float64

In [17]:
df_clean = df_clean[df_clean["UnitPrice"] > 0].copy()

In [18]:
df_clean.shape

(397884, 8)

In [19]:
df_clean["Revenue"] = df_clean["Quantity"] * df_clean["UnitPrice"]

In [20]:
df_clean.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34

In [21]:
df_clean["Revenue"].describe()

count    397884.000000
mean         22.397000
std         309.071041
min           0.001000
25%           4.680000
50%          11.800000
75%          19.800000
max      168469.600000
Name: Revenue, dtype: float64

In [22]:
df_clean["Revenue"].sum()

np.float64(8911407.904)

In [91]:
df_clean["CustomerID"].nunique()

4338

In [24]:
df_clean["StockCode"].nunique()

3665

In [25]:
df_clean["InvoiceNo"].nunique()

18532

In [26]:
df_clean[["CustomerID", "StockCode", "Description", "InvoiceNo", "Revenue"]].head(10)

,CustomerID,StockCode,Description,InvoiceNo,Revenue
0,17850.0,85123A,WHITE HANGING HEART T-LIGHT HOLDER,536365,15.30
1,17850.0,71053,WHITE METAL LANTERN,536365,20.34
2,17850.0,84406B,CREAM CUPID HEARTS COAT HANGER,536365,22.00
3,17850.0,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,536365,20.34
4,17850.0,84029E,RED WOOLLY HOTTIE WHITE HEART.,536365,20.34
5,17850.0,22752,SET 7 BABUSHKA NESTING BOXES,536365,15.30
6,17850.0,21730,GLASS STAR FROSTED T-LIGHT HOLDER,536365,25.50
7,17850.0,22633,HAND WARMER UNION JACK,536366,11.10
8,17850.0,22632,HAND WARMER RED POLKA DOT,536366,11.10
9,13047.0,84879,ASSORTED COLOUR BIRD ORNAMENT,536367,54.08

In [27]:
invoice_product_count = (
    df_clean.groupby("InvoiceNo")["StockCode"]
    .nunique()
)

invoice_product_count.describe()

count    18532.000000
mean        20.928178
std         23.816197
min          1.000000
25%          6.000000
50%         15.000000
75%         27.000000
max        541.000000
Name: StockCode, dtype: float64

In [28]:
invoice_product_count.head(10)

InvoiceNo
536365     7
536366     2
536367    12
536368     4
536369     1
536370    20
536371     1
536372     2
536373    16
536374     1
Name: StockCode, dtype: int64

In [29]:
invoice_product_count[invoice_product_count > 100].count()

np.int64(207)

In [30]:
invoice_product_count[invoice_product_count > 50].count()

np.int64(1506)

In [31]:
invoice_product_count[invoice_product_count == 1].count()

np.int64(1407)

In [32]:
valid_invoices = invoice_product_count[
    (invoice_product_count >= 2) &
    (invoice_product_count <= 50)
].index

In [33]:
len(valid_invoices)

15619

In [34]:
df_pairs = df_clean[
    df_clean["InvoiceNo"].isin(valid_invoices)
][["InvoiceNo", "StockCode", "Description"]].drop_duplicates()

In [35]:
df_pairs.shape

(268849, 3)

In [36]:
df_pairs.head(10)

  InvoiceNo StockCode                          Description
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER
1    536365     71053                  WHITE METAL LANTERN
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.
5    536365     22752         SET 7 BABUSHKA NESTING BOXES
6    536365     21730    GLASS STAR FROSTED T-LIGHT HOLDER
7    536366     22633               HAND WARMER UNION JACK
8    536366     22632            HAND WARMER RED POLKA DOT
9    536367     84879        ASSORTED COLOUR BIRD ORNAMENT

In [41]:
df_pairs["StockCode"] = df_pairs["StockCode"].astype(str)

In [42]:
from itertools import combinations

product_pairs = []

for invoice, group in df_pairs.groupby("InvoiceNo"):
    products = group["StockCode"].unique()

    for product_a, product_b in combinations(sorted(products), 2):
        product_pairs.append((invoice, product_a, product_b))

In [44]:
pairs_df = pd.DataFrame(
    product_pairs,
    columns=["InvoiceNo", "Product_A", "Product_B"]
)
pairs_df.shape

(3268900, 3)

In [45]:
pairs_df.head(20)

    InvoiceNo Product_A Product_B
0      536365     21730     22752
1      536365     21730     71053
2      536365     21730    84029E
3      536365     21730    84029G
4      536365     21730    84406B
5      536365     21730    85123A
6      536365     22752     71053
7      536365     22752    84029E
8      536365     22752    84029G
9      536365     22752    84406B
10     536365     22752    85123A
11     536365     71053    84029E
12     536365     71053    84029G
13     536365     71053    84406B
14     536365     71053    85123A
15     536365    84029E    84029G
16     536365    84029E    84406B
17     536365    84029E    85123A
18     536365    84029G    84406B
19     536365    84029G    85123A

In [58]:
pair_counts = (
    pairs_df
    .groupby(["Product_A", "Product_B"])
    .size()
    .reset_index(name="Purchase_Count")
)

In [59]:
pair_counts = pair_counts.sort_values(
    "Purchase_Count",
    ascending=False
)

In [60]:
pair_counts.head(20)

        Product_A Product_B  Purchase_Count
913323      22697     22699             428
748824      22386    85099B             415
928551      22726     22727             410
913322      22697     22698             368
1100075     23203    85099B             356
82024       20725     22384             352
1193674     82482    82494L             350
81223       20725     20727             346
82023       20725     22383             346
914420      22698     22699             342
763357      22423     22699             331
585334      22086     22910             325
518858      21931    85099B             320
1098880     23202     23203             320
81224       20725     20728             316
1099465     23203     23209             314
1213066    85099B    85099F             313
86313       20727     22384             310
88464       20728     22383             307
82022       20725     22382             304

In [61]:
product_order_count = (
    df_pairs
    .groupby("StockCode")["InvoiceNo"]
    .nunique()
    .reset_index(name="Order_Count")
)
product_order_count.head()

  StockCode  Order_Count
0     10002           36
1     10080           16
2     10120           12
3    10123C            3
4    10124A            3

In [62]:
product_order_count.shape

(3577, 2)

In [75]:
# Create product pair counts
pair_counts = (
    pairs_df
    .groupby(["Product_A", "Product_B"])
    .size()
    .reset_index(name="Purchase_Count")
)

# Prepare product order counts
product_counts = product_order_count.rename(
    columns={
        "StockCode": "Product_A",
        "Order_Count": "Product_A_Order_Count"
    }
)

# Keep only the columns we need
product_counts = product_counts[
    ["Product_A", "Product_A_Order_Count"]
]

# Merge
pair_counts = pair_counts.merge(
    product_counts,
    on="Product_A",
    how="left"
)

# Calculate confidence
pair_counts["Confidence"] = (
    pair_counts["Purchase_Count"] /
    pair_counts["Product_A_Order_Count"]
)

# Sort by highest confidence
pair_counts = pair_counts.sort_values(
    "Confidence",
    ascending=False
)

# Show top 20
pair_counts.head(20)

        Product_A Product_B  Purchase_Count  Product_A_Order_Count  Confidence
1216558    90214T    90214U               1                      1         1.0
1215221    90059C    90059E               1                      1         1.0
1215220    90059B     90208               1                      1         1.0
36583       17001         M               1                      1         1.0
36582       17001    85230G               1                      1         1.0
36581       17001    85230E               1                      1         1.0
1216570    90214W    90214Y               1                      1         1.0
312219      21416     21617               2                      2         1.0
20669       16043     22161               2                      2         1.0
303678      21393     21399               2                      2         1.0
303682      21393     21439               2                      2         1.0
303685      21393     21586               2                      2         1.0
303633      21392     21398               3                      3         1.0
824064      22538     22544               6                      6         1.0
622827      22146    47586A               1                      1         1.0
622828      22146     84580               1                      1         1.0
1170789    35607A    82613C               1                      1         1.0
1170790    35607A    82613D               1                      1         1.0
1170791    35607A     84799               1                      1         1.0
1170792    35607A     84819               1                      1         1.0

In [76]:
# Number of valid invoices used for our pair analysis
total_orders = len(valid_invoices)

# Calculate how many orders contain each Product B
product_b_counts = (
    df_pairs[df_pairs["InvoiceNo"].isin(valid_invoices)]
    .groupby("StockCode")["InvoiceNo"]
    .nunique()
    .reset_index(name="Product_B_Order_Count")
)

# Rename StockCode so we can merge it with Product_B
product_b_counts = product_b_counts.rename(
    columns={"StockCode": "Product_B"}
)

# Calculate support of Product B
product_b_counts["Support_B"] = (
    product_b_counts["Product_B_Order_Count"] / total_orders
)

# Merge Product B information
pair_counts = pair_counts.merge(
    product_b_counts[["Product_B", "Support_B"]],
    on="Product_B",
    how="left"
)

# Calculate Lift
pair_counts["Lift"] = (
    pair_counts["Confidence"] /
    pair_counts["Support_B"]
)

# Sort by highest Lift
pair_counts = pair_counts.sort_values(
    "Lift",
    ascending=False
)

# Show top 20
pair_counts.head(20)

,Product_A,Product_B,Purchase_Count,Product_A_Order_Count,Confidence,Support_B,Lift
65,90059B,90059C,1,1,1.0,0.000064,15619.0
1379,90199A,90199B,1,1,1.0,0.000064,15619.0
66,90059B,90059E,1,1,1.0,0.000064,15619.0
94,90039A,90039B,1,1,1.0,0.000064,15619.0
95,90039A,90039D,1,1,1.0,0.000064,15619.0
137,90028,90074,1,1,1.0,0.000064,15619.0
843,90141A,90141C,1,1,1.0,0.000064,15619.0
1527,90214O,90214W,1,1,1.0,0.000064,15619.0
1579,35597A,35597B,1,1,1.0,0.000064,15619.0
1525,90214O,90214U,1,1,1.0,0.000064,15619.0
1552,90214O,90214Z,1,1,1.0,0.000064,15619.0
153,90026C,90050,1,1,1.0,0.000064,15619.0
142,90029,90055,1,1,1.0,0.000064,15619.0
144,90027A,90027D,1,1,1.0,0.000064,15619.0
837,90141C,90185A,1,1,1.0,0.000064,15619.0
849,90141A,90185A,1,1,1.0,0.000064,15619.0
848,90141A,90183C,1,1,1.0,0.000064,15619.0
546,90000D,90012A,1,1,1.0,0.000064,15619.0
1663,90214U,90214Z,1,1,1.0,0.000064,15619.0
840,90138,90163B,1,1,1.0,0.000064,15619.0

In [77]:
strong_pairs = pair_counts[
    pair_counts["Purchase_Count"] >= 20
].copy()

In [78]:
strong_pairs = strong_pairs.sort_values(
    "Lift",
    ascending=False
)

In [79]:
strong_pairs.head(20)

,Product_A,Product_B,Purchase_Count,Product_A_Order_Count,Confidence,Support_B,Lift
1864,22344,22345,21,30,0.700000,0.001793,390.475000
1794,21400,21401,24,32,0.750000,0.001985,377.879032
1747,35809A,35810A,26,32,0.812500,0.002369,342.984797
1760,23554,23556,28,36,0.777778,0.002305,337.447531
1859,23555,23556,26,37,0.702703,0.002305,304.875375
2064,22514,22515,30,47,0.638298,0.002177,293.222778
1971,23055,23057,20,30,0.666667,0.002305,289.240741
2308,22450,22451,21,38,0.552632,0.001921,287.718421
1755,22518,22519,31,39,0.794872,0.002817,282.161422
5196,22514,22516,22,47,0.468085,0.001665,281.193126
1748,21788,21789,34,42,0.809524,0.002945,274.868530
1880,23564,23566,24,35,0.685714,0.002497,274.619780
2346,23555,23558,20,37,0.540541,0.002049,263.834459
2121,23554,23555,22,36,0.611111,0.002369,257.971471
1757,21088,21096,45,57,0.789474,0.003201,246.615789
5216,22343,22344,20,43,0.465116,0.001921,242.155039
1786,23451,23452,21,28,0.750000,0.003265,229.691176
2190,22524,22525,29,49,0.591837,0.002625,225.460926
2042,21926,21927,25,38,0.657895,0.002945,223.383867
5187,23452,23453,24,51,0.470588,0.002113,222.730838

In [80]:
# Strong practical recommendations
recommended_pairs = pair_counts[
    (pair_counts["Purchase_Count"] >= 100) &
    (pair_counts["Confidence"] >= 0.30)
].copy()

# Sort by confidence first, then purchase count
recommended_pairs = recommended_pairs.sort_values(
    ["Confidence", "Purchase_Count"],
    ascending=[False, False]
)

recommended_pairs.head(20)

,Product_A,Product_B,Purchase_Count,Product_A_Order_Count,Confidence,Support_B,Lift
1693,22916,22917,116,123,0.943089,0.008067,116.905665
1694,22917,22920,116,126,0.920635,0.008067,114.122197
1696,22916,22920,113,123,0.918699,0.008067,113.882243
1695,22918,22920,113,123,0.918699,0.008067,113.882243
1697,22919,22920,114,125,0.912000,0.008067,113.051810
1698,22916,22918,112,123,0.910569,0.007875,115.627470
1699,22917,22919,114,126,0.904762,0.008003,113.051810
1700,22918,22919,111,123,0.902439,0.008003,112.761561
1704,22916,22919,110,123,0.894309,0.008003,111.745691
1705,22917,22918,112,126,0.888889,0.007875,112.874435
1743,22746,22748,127,155,0.819355,0.014213,57.646411
1751,21086,21094,172,215,0.800000,0.015494,51.633058
1759,22698,22699,342,439,0.779043,0.040271,19.344796
1765,22745,22748,160,206,0.776699,0.014213,54.645325
1767,22302,22303,118,152,0.776316,0.011845,65.542034
1768,23174,23175,163,210,0.776190,0.013765,56.387530
1769,23254,23256,149,192,0.776042,0.014406,53.871088
1771,22697,22699,428,553,0.773960,0.040271,19.218577
1772,23171,23172,158,205,0.770732,0.011140,69.184244
1777,84997C,84997D,170,226,0.752212,0.020104,37.416577

In [81]:
product_names = (
    df_clean[["StockCode", "Description"]]
    .dropna()
    .drop_duplicates("StockCode")
)

product_names["StockCode"] = product_names["StockCode"].astype(str)

recommended_pairs_named = recommended_pairs.merge(
    product_names.rename(
        columns={
            "StockCode": "Product_A",
            "Description": "Product_A_Name"
        }
    ),
    on="Product_A",
    how="left"
)

recommended_pairs_named = recommended_pairs_named.merge(
    product_names.rename(
        columns={
            "StockCode": "Product_B",
            "Description": "Product_B_Name"
        }
    ),
    on="Product_B",
    how="left"
)

recommended_pairs_named[
    [
        "Product_A",
        "Product_A_Name",
        "Product_B",
        "Product_B_Name",
        "Purchase_Count",
        "Confidence",
        "Lift"
    ]
].head(20)

,Product_A,Product_A_Name,Product_B,Product_B_Name,Purchase_Count,Confidence,Lift
0,22916,HERB MARKER THYME,22917,HERB MARKER ROSEMARY,116,0.943089,116.905665
1,22917,HERB MARKER ROSEMARY,22920,HERB MARKER BASIL,116,0.920635,114.122197
2,22916,HERB MARKER THYME,22920,HERB MARKER BASIL,113,0.918699,113.882243
3,22918,HERB MARKER PARSLEY,22920,HERB MARKER BASIL,113,0.918699,113.882243
4,22919,HERB MARKER MINT,22920,HERB MARKER BASIL,114,0.912000,113.051810
5,22916,HERB MARKER THYME,22918,HERB MARKER PARSLEY,112,0.910569,115.627470
6,22917,HERB MARKER ROSEMARY,22919,HERB MARKER MINT,114,0.904762,113.051810
7,22918,HERB MARKER PARSLEY,22919,HERB MARKER MINT,111,0.902439,112.761561
8,22916,HERB MARKER THYME,22919,HERB MARKER MINT,110,0.894309,111.745691
9,22917,HERB MARKER ROSEMARY,22918,HERB MARKER PARSLEY,112,0.888889,112.874435
10,22746,POPPY'S PLAYHOUSE LIVINGROOM,22748,POPPY'S PLAYHOUSE KITCHEN,127,0.819355,57.646411
11,21086,SET/6 RED SPOTTY PAPER CUPS,21094,SET/6 RED SPOTTY PAPER PLATES,172,0.800000,51.633058
12,22698,PINK REGENCY TEACUP AND SAUCER,22699,ROSES REGENCY TEACUP AND SAUCER,342,0.779043,19.344796
13,22745,POPPY'S PLAYHOUSE BEDROOM,22748,POPPY'S PLAYHOUSE KITCHEN,160,0.776699,54.645325
14,22302,COFFEE MUG PEARS DESIGN,22303,COFFEE MUG APPLES DESIGN,118,0.776316,65.542034
15,23174,REGENCY SUGAR BOWL GREEN,23175,REGENCY MILK JUG PINK,163,0.776190,56.387530
16,23254,CHILDRENS CUTLERY DOLLY GIRL,23256,CHILDRENS CUTLERY SPACEBOY,149,0.776042,53.871088
17,22697,GREEN REGENCY TEACUP AND SAUCER,22699,ROSES REGENCY TEACUP AND SAUCER,428,0.773960,19.218577
18,23171,REGENCY TEA PLATE GREEN,23172,REGENCY TEA PLATE PINK,158,0.770732,69.184244
19,84997C,BLUE 3 PIECE POLKADOT CUTLERY SET,84997D,PINK 3 PIECE POLKADOT CUTLERY SET,170,0.752212,37.416577

In [82]:
# Final recommendation dataset
final_recommendations = recommended_pairs_named[
    (recommended_pairs_named["Purchase_Count"] >= 100) &
    (recommended_pairs_named["Confidence"] >= 0.30)
].copy()

# Select only useful columns
final_recommendations = final_recommendations[
    [
        "Product_A",
        "Product_A_Name",
        "Product_B",
        "Product_B_Name",
        "Purchase_Count",
        "Confidence",
        "Lift"
    ]
]

# Sort by strongest practical recommendations
final_recommendations = final_recommendations.sort_values(
    ["Purchase_Count", "Confidence"],
    ascending=[False, False]
)

final_recommendations.head(20)

,Product_A,Product_A_Name,Product_B,Product_B_Name,Purchase_Count,Confidence,Lift
17,22697,GREEN REGENCY TEACUP AND SAUCER,22699,ROSES REGENCY TEACUP AND SAUCER,428,0.773960,19.218577
47,22386,JUMBO BAG PINK POLKADOT,85099B,JUMBO BAG RED RETROSPOT,415,0.600579,7.368768
32,22726,ALARM CLOCK BAKELIKE GREEN,22727,ALARM CLOCK BAKELIKE RED,410,0.663430,15.039361
31,22697,GREEN REGENCY TEACUP AND SAUCER,22698,PINK REGENCY TEACUP AND SAUCER,368,0.665461,23.676167
141,23203,JUMBO BAG DOILEY PATTERNS,85099B,JUMBO BAG RED RETROSPOT,356,0.416862,5.114662
195,20725,LUNCH BAG RED RETROSPOT,22384,LUNCH BAG PINK POLKADOT,352,0.368201,8.648013
71,82482,WOODEN PICTURE FRAME WHITE FINISH,82494L,WOODEN FRAME ANTIQUE WHITE,350,0.527108,12.863917
202,20725,LUNCH BAG RED RETROSPOT,22383,LUNCH BAG SUKI DESIGN,346,0.361925,7.618466
203,20725,LUNCH BAG RED RETROSPOT,20727,LUNCH BAG BLACK SKULL.,346,0.361925,7.597986
12,22698,PINK REGENCY TEACUP AND SAUCER,22699,ROSES REGENCY TEACUP AND SAUCER,342,0.779043,19.344796
126,22086,PAPER CHAIN KIT 50'S CHRISTMAS,22910,PAPER CHAIN KIT VINTAGE CHRISTMAS,325,0.435074,13.018036
61,21931,JUMBO STORAGE BAG SUKI,85099B,JUMBO BAG RED RETROSPOT,320,0.547009,6.711490
68,23202,JUMBO BAG VINTAGE LEAF,23203,JUMBO BAG DOILEY PATTERNS,320,0.534224,9.770539
238,20725,LUNCH BAG RED RETROSPOT,20728,LUNCH BAG CARS BLUE,316,0.330544,7.417767
198,23203,JUMBO BAG DOILEY PATTERNS,23209,LUNCH BAG DOILEY PATTERN,314,0.367681,7.750091
142,20727,LUNCH BAG BLACK SKULL.,22384,LUNCH BAG PINK POLKADOT,310,0.416667,9.786341
121,20728,LUNCH BAG CARS BLUE,22383,LUNCH BAG SUKI DESIGN,307,0.441092,9.284926
125,20728,LUNCH BAG CARS BLUE,22384,LUNCH BAG PINK POLKADOT,304,0.436782,10.258785
250,20725,LUNCH BAG RED RETROSPOT,22382,LUNCH BAG SPACEBOY DESIGN,304,0.317992,7.261274
24,23300,GARDENERS KNEELING PAD CUP OF TEA,23301,GARDENERS KNEELING PAD KEEP CALM,303,0.707944,20.942000

In [84]:
import os

# Create data folder if it doesn't exist
os.makedirs("data", exist_ok=True)

# Save recommendation data
final_recommendations.to_csv(
    "data/product_relationships.csv",
    index=False
)

print("Saved successfully!")
print("Shape:", final_recommendations.shape)

Saved successfully!
Shape: (265, 7)

In [85]:
import pandas as pd

test = pd.read_csv("data/product_relationships.csv")

print(test.shape)
test.head()

(265, 7)

,Product_A,Product_A_Name,Product_B,Product_B_Name,Purchase_Count,Confidence,Lift
0,22697,GREEN REGENCY TEACUP AND SAUCER,22699,ROSES REGENCY TEACUP AND SAUCER,428,0.773960,19.218577
1,22386,JUMBO BAG PINK POLKADOT,85099B,JUMBO BAG RED RETROSPOT,415,0.600579,7.368768
2,22726,ALARM CLOCK BAKELIKE GREEN,22727,ALARM CLOCK BAKELIKE RED,410,0.663430,15.039361
3,22697,GREEN REGENCY TEACUP AND SAUCER,22698,PINK REGENCY TEACUP AND SAUCER,368,0.665461,23.676167
4,23203,JUMBO BAG DOILEY PATTERNS,85099B,JUMBO BAG RED RETROSPOT,356,0.416862,5.114662

In [87]:
os.makedirs("data", exist_ok=True)